services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    ports:
      - 3000:80
    environment:
      - PORT=80
      - DB_URL=postgresql://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}
    develop:
      watch:
        - action: sync
          path: ./src
          target: /app/src
    # volumes:
    #   - ./src:/app/src
    depends_on:
      - db
    networks:
      - config-store-net

  db:
    image: postgres:17.1
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - type: volume
        source: helm-lauro-postgres-data
        target: /var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - config-store-net

networks:
  config-store-net:

volumes:
  helm-lauro-postgres-data: